### PR TITLE
Add github actions and all cleanup tools

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Comment by persianpros** [comment]
@Huevos 

This what we use at OV and will help you with all builds/checks/cleanups.

First I sent it for this repo then I can send it for your other repos as well if you like the results but you could see some of them on our git or OE-A (plugins).

**Comment by TwolDE2** [comment]
Vix-core is already python3/python2 compatible no need for all these tools

**Comment by persianpros** [comment]
@TwolDE2 

You think, after this you'll see ;)

**Comment by RobvanderDoes** [comment]
Should we close this PR?

**Pull request closed without merging**
