### PR TITLE
Use a file for the names of backup entities so that we can handle spa…

### PR DESCRIPTION
**Pull request by original-birdman**
…ces and active command line characters.

### CODE REVIEW

**Comment by Huevos** [comment]
Hi Gordon, is this the commit for this bug?

https://www.world-of-satellite.com/showthread.php?62095-Backup-can-t-handle-spaces-(or-active-commandline-characters)-in-items

**Comment by original-birdman** [comment]
Yes.

**Comment by original-birdman** [comment]
Is there an issue, or is this still in a queue?

**Comment by Huevos** [comment]
No queue or issue.

**Pull request merged**
