### PR TITLE
Enable a GUI error message for users on an unsupported box type.

### PR DESCRIPTION
**Pull request by original-birdman**
(also trims some trailing spaces on 2 lines).

http://www.world-of-satellite.com/showthread.php?55116-Image-Manager-Downloads-(Couch-Flash)-problems&p=435265&viewfull=1#post435265

### CODE REVIEW

**Comment by andyblac** [comment]
instead of try / except, could recode to use something like 

```
# Ensure this item is missing before we check box support...
if hasattr(self, "_error_message"):
	del self._error_message

if getMachineMake() in supportedMachines.keys():
	self.boxtype = supportedMachines[getMachineMake()]
else:
	print "[ImageManager][populate_List] the %s is not currently supported by OpenViX." % getMachineMake()
	self._error_message =  _("The %s is not currently supported by OpenViX.") % getMachineMake()
	self["key_green"].setText(_("Show Error"))
	self["key_green"].show()
	self.emlist.append(_("**ERROR**"))
	self["list"].setList(self.emlist)
	self["list"].show()
	return
````

**Comment by original-birdman** [comment]
Except it's more pythonish to use try/except.

`hasattr()` actually works by accessing the member and trapping any error, so try/except is simpler and quicker.

**Comment by andyblac** [comment]
try / except is lazy code. sorry not going to accept this.

**Comment by original-birdman** [comment]
try / except is _not_ lazy code. It's the **correct** thing to do for code which you expect to work most of the time as it avoids you testing for something which will succeed in the majority of occasions.

Unless you mean that it should be:
`except AttributeError:`
rather than just
`except:`
but given the simplicity of the code that seems a little excessive.

**Comment by Huevos** [comment]
Gordon, try/except is marginally faster on success and slower by miles on failure. It also hides errors.

Use try/except where a race condition exists (i.e. opening a file, where the file may have been deleted between the test and trying to open it) or when the result is outside your control, e.g. opening a web page.

But for things inside your control I can't see a reason not to test.

**Comment by original-birdman** [comment]
This test _isn't expected to fail_ - hence the try/except.
The code was there so that any typo would result in an error message rather than a blank screen.
A typo **had** occurred (see the original comment) - hence this fix and the style of this fix.

**Comment by original-birdman** [comment]
> try/except is marginally faster on success and slower by miles on failure

The timings given here imply that you'll gain overall with try/except if the exception occurs in less than ~12% of the attempts. I'm expecting < 0.01%.

**Comment by original-birdman** [comment]
> try/except is marginally faster on success and slower by miles on failure

The timings given here imply that you'll gain overall with try/except if the exception occurs in less than ~12% of the attempts. I'm expecting < 0.01%.

https://stackoverflow.com/questions/903130/hasattr-vs-try-except-block-to-deal-with-non-existent-attributes

**Comment by Huevos** [comment]
If your sole purpose is speed use getattr(). It is faster on success and failure then try/except is on success.

**Comment by original-birdman** [comment]
That's no good as I'm trying to _delete_ that attribute if it exists - any existing value is irrelevant.

It would be better if python had a means of deleting an attribute _without_ raising an error when it doesn't exist.

**Pull request closed without merging**
