### PR TITLE
Update pot and po files

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Comment by persianpros** [comment]
@AbuBaniaz @Huevos 

And this is the file I used for vix-core:

[updateallpo-multiOS.zip](https://github.com/OpenViX/vix-core/files/6356570/updateallpo-multiOS.zip)

**Comment by persianpros** [comment]
Should I close this PR?

All po/pot files updated also the tool is here if you want to put it in the repo.

**Comment by Huevos** [comment]
The PR is merged. Thanks for the file.

BTW, there is a problem building the proc module in "nextp3 branch. I can post the output if you are interested.

**Comment by persianpros** [comment]
@Huevos 

For which model? If it's with kernel 5.12 like edision 4k then https://github.com/OpenVisionE2/openvision-module/commit/7b335e9a1f149ea0bf262a6e910b3fae17b4d86a needed.

**Comment by Huevos** [comment]
@persionpros

Have you added me a a github blacklistee?

OS Mio 4k plus. It builds ok with the patch. Thanks.

**Comment by persianpros** [comment]
@Huevos 

I don't have a blacklist, you have access to our git.

**Comment by Huevos** [comment]
I don't mean the public repos.

https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-personal-account

**Comment by persianpros** [comment]
Still you're not blocked not even on my personal git.

**Comment by Huevos** [comment]
Ok, something strange happening because I am barred from leaving comments in your PR's on PLi. Anyway not important.

**Comment by persianpros** [comment]
That's weird, maybe the closed something?

**Pull request merged**
